name: Eleventy Build
on:
  push:
    branches:
      - source  # default branch
  pull_request:
    branches:
      - source

jobs:
  build_deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.2.0
        with:
          submodules: true

      - name: Build HTML pages using eleventy
        uses: TartanLlama/actions-eleventy@v1.2

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          publish_dir: _site
          publish_branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
