name: Eleventy Build
on:
  push:
    branches:
      - source  # default branch

jobs:
  build_deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.2.0
      - name: Build
        uses: TartanLlama/actions-eleventy@v1.2
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          publish_dir: _site
          publish_branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
